# .github/workflows/branch-protection.yml
name: Enforce PR to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-push:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent Direct Push
        run: |
          if [ "$GITHUB_EVENT_NAME" != "pull_request" ]; then
            echo "Direct pushes to the main branch are not allowed. Please use a pull request."
            exit 1
          fi
